name: pages-build-deployment
on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Mona the Octocat"
      home:
        description: "location"
        required: false
        default: "The Octoverse"
permissions: write-all
